### ISSUE TITLE
this pointer used incorrectly in forEach

### ISSUE THREAD

**Issue by sdetweil** [WouterEekhout/MMM-Tado#11]
in the forEach() (line 47 of MMM-Tado.js) loop thru the zone info, one of the this.config.units uses self (line 69) (set on line 32) , the rest (4) use this.config.units, (lines 98, 121, 161, and 190)

but... unless you specifically pass the second parm (after the function) in the forEach invocation  'this' is undefined inside the foreach , so the test fails, and the result is Fahrenheit display is selected

see 22.1.3.12 Array.prototype.forEach
https://tc39.es/ecma262/#sec-ecmascript-language-statements-and-declarations

the 4 statements should be changed to self.config.units

**Comment by WouterEekhout** [comment]
@sdetweil Good find!
