### ISSUE TITLE
Module displays in Fahrenheit even when unit is explicitly called out

### ISSUE THREAD

**Issue by Krisalexroberts** [WouterEekhout/MMM-Tado#12]
The module displays in Fahrenheit despite being configured in metric

Config: 

```
var config = {
	address: "Redacted", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	port: 8080,
	ipWhitelist: [], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	timeFormat: 24,
	units: "metric",     // Called out in base config
```

```
       {
            module: 'MMM-Tado',
            position: 'top_right', // This can be any of the regions.
            config: {
                username: 'RED@CTED', 
                password: 'REDACTED', 
                updateInterval: 300000,
                units: 'metric'.       // Called out in Module
            }
        },
```

<img width="198" alt="Screenshot 2020-07-24 at 08 32 00" src="https://user-images.githubusercontent.com/26844453/88369662-6b707580-cd88-11ea-96d0-8286a9fe2c43.png">

**Comment by WouterEekhout** [comment]
This issue has been requested before see ticket #9 and https://forum.magicmirror.builders/topic/12914/mmm-tado-wrong-units/4?_=1590847553898.

I was unable to fix it then, because I cannot replicate the problem. I am using the metric system myself. I still don't have a clue why it doesn't work properly.

BTW the `units`-config in the module config can be removed. Just the base config is enough.
```
    {
            module: 'MMM-Tado',
            position: 'top_right', // This can be any of the regions.
            config: {
                username: 'RED@CTED', 
                password: 'REDACTED', 
                updateInterval: 300000,
                units: 'metric'.       // THIS LINE CAN BE REMOVED
            }
        },
```

**Comment by Krisalexroberts** [comment]
Adding `var self = this` worked, do you want me to raise a pull request?

**Comment by WouterEekhout** [comment]
For this message I assume the following:

1. You add the line `var self = this` to the beginning of the start function
2. You have the `units: 'metric' set in de module config

If the above is correct, then the code will read out the units from the module config. Did you try it with just the units in the base config?

**Comment by Krisalexroberts** [comment]
Yes, tried it with the base config, and it didn't help. One thing I did change yesterday was adding 1 modules, MMM-WeatherOrNot, it seemed to be a similar time to it changing to imperial.

Both assumptions above are correct

**Comment by WouterEekhout** [comment]
Can you comment out other modules and restart the mirror? Does this affect the units?
