### ISSUE TITLE
Blank screen on Magic Mirror

### ISSUE THREAD

**Issue by Craig6580** [WouterEekhout/MMM-Tado#13]
Hi all, 

I would love to use this module, but I just can't get it working. It just blanks the entire MM. If i comment out the config lines, then everything else on the MM comes back. I don't even get the config error screen. I can get all the Tado website API info manually using the links provided in the previous issue.

Any help would be greatly appreciated, I am quite new to this....

              `{
                        module: "MMM-Tado",
                        position: "bottom_right",
                        config: {
                                username: "MY TADO USERNAME (EMAIL)",
                                password: "MY TADO PASSWORD",
                                updateInterval: 300000
                                }
                },`

**Comment by WouterEekhout** [comment]
Did you ran `npm install` from inside the MMM-Tado's folder?

**Comment by Craig6580** [comment]
THANK YOU! I thought I had, but maybe not from inside the MMM-Tado directory. This fixed the issue:

`cd ~/MagicMirror/modules/MM-Tado`
`npm install`

Would you consider adding the top line to the installation instructions? It might seem obvious to seasoned CLI users, but I am still learning.
