### ISSUE TITLE
Heating symbol

### ISSUE THREAD

**Issue by mishu28nmv** [WouterEekhout/MMM-Tado#14]
Hi and thank you for this. It shows current temp and target temp, but it doesn't show the heating symbol and the Home name. This is my config:
`module: 'MMM-Tado',
		position: 'bottom_left', // This can be any of the regions.
		config: {
		username: 'username', 
		password: 'password', 
		updateInterval: 300000`

**Comment by WouterEekhout** [comment]
The symbols only shows when the heater is active. When it is not active the symbol does not show.

**Comment by mecco86** [comment]
HI and thanks for your work. I’ve a tado Smartthermostat and 6 head in 6 zone, but module show info only thermostat. Can i show the zone?

**Comment by rafaelcarneiromachado** [comment]
Even with **global** variable set as **units: 'metric'** it keeps showing me in fahrenheit

**Comment by mishu28nmv** [comment]
> The symbols only shows when the heater is active. When it is not active the symbol does not show.

Thank you. Your module works great. Can you tell me, if I want the heat symbol to be the color RED, where and what can I edit?

EDIT: Nevermind, just add in /modules/mmm-tado/css/mmm-tado.css this lines
.fa-fire {
color: #ff0000;
}
