### ISSUE TITLE
Target temperature - shown after current temperature

### ISSUE THREAD

**Issue by dinkybluebug** [WouterEekhout/MMM-Tado#3]
Not so much of a bug but more of a feature request - so not sure this belongs here.  Happy to close and raise somewhere else.

Great module by the way - it would be awesome if it should show the target temperature  after the current temperature.  (maybe in a smaller size)

Data is held here as 'celcius'

  "setting": {
    "type": "HEATING",
    "power": "ON",
    "temperature": {
      "celsius": 21,
      "fahrenheit": 69.8
    }

It would be useful as this replicates the data shown in the tado app.

**Comment by WouterEekhout** [comment]
I agree, it should be in there. It will be implemented.

**Comment by WouterEekhout** [comment]
The code has been updated It will show the target temperature, see image below. Can you verify that it works for you?

![screenshot](https://cloud.githubusercontent.com/assets/5739335/21907031/14873d70-d90e-11e6-9ce3-e5017b900c3e.png)

**Comment by dinkybluebug** [comment]
Yay! yes that's awesome!

You work fast - I wish I had the skill to do that... everything is such a learning process for me at the moment

**Comment by WouterEekhout** [comment]
Thank you! Well, it has been my job for the last 8 years. That helps ;)
