### ISSUE TITLE
Ability to hide humidity

### ISSUE THREAD

**Issue by dinkybluebug** [WouterEekhout/MMM-Tado#4]
Hi - more of a enhancement than bug - It would be great if one of the config options was to hide Humidity.  I dont really refer or look at this data.

I realise that this is quite personal - so feel free to ignore - ha!

Still a great module by the way!

**Comment by dinkybluebug** [comment]
Ive tried to hide using CSS - but I dont think it has its own class name?  (not sure Ive used the right terminology there

**Comment by WouterEekhout** [comment]
Hi it is not something I'm going to implement. If you don't want it you can Comment out the following code in `MMM-Tado.js` (line 156-165):

`                    var breakLine = document.createElement("br");
                    secondTableDateWrapper.appendChild(breakLine);

                    var humidityWrapper = document.createElement("span");
                    var humidityIconWrapper = document.createElement("i");
                    humidityIconWrapper.className = "fa fa-tint";
                    humidityWrapper.appendChild(humidityIconWrapper);
                    var humidityTextWrapper = document.createTextNode(zone.state.sensorDataPoints.humidity.percentage + "%");
                    humidityWrapper.appendChild(humidityTextWrapper);
                    secondTableDateWrapper.appendChild(humidityWrapper);`

**Comment by dinkybluebug** [comment]
Thanks for the reply. Much appreciated. I have a different setup on my mirror and I'm short of available display space.
