### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by mirko3000** [WouterEekhout/MMM-Tado#7]
Hi,

recently I am getting a CORS issue with the Tado module:

Failed to load https://my.tado.com/api/v2/me?password=xyz&username=xyz: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

Not sure what changed, it worked just fine before - maybe changed security settings?
Any quick fix to get around this?

Best regards,
Mirko

**Comment by WouterEekhout** [comment]
Hi,

I am having the same issue since today. I don't know a fix yet. If I read the [information link](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin) it looks like a header needs needs to be set on the Tado's servers. 

Unfortunately I cannot look into it further this weekend.

**Comment by mirko3000** [comment]
As far as I read you could extract the API-call to a node_helper module, there you will not face any CORS issues.

**Comment by mirko3000** [comment]
Found a dirty fix: add this line to the electronOptionsDefaults in electron.js:

`webPreferences: { webSecurity: false }`

This will disable CORS check in the electron browser - but also disabling security ;-)

**Comment by WouterEekhout** [comment]
I've started using the node_helper. This should solve the problem.

**Comment by a-wenzel** [comment]
hi,

it seems like a first call is missing?! After a restart it takes some time to show Tado.

**Comment by WouterEekhout** [comment]
@a-wenzel I cannot reproduce the problem. How long does it take? Seconds or minutes? If you see the results after 5 minutes, then something goes wrong during the first call. It should be started after 3 seconds.

**Comment by a-wenzel** [comment]
@WouterEekhout after a restart it takes ~30 seconds to show up (logo from block is also not displayed before)...

and i get every 1 - 5 minutes this error (Chrome Console):

`
MMM-Tado.js:97 Uncaught (in promise) TypeError: Cannot read property 'insideTemperature' of undefined
    at MMM-Tado.js:97
    at Array.forEach (<anonymous>)
    at MMM-Tado.js:45
    at Array.forEach (<anonymous>)
    at Class.getDom (MMM-Tado.js:34)
    at main.js:110
    at new Promise (<anonymous>)
    at updateDom (main.js:109)
    at Object.updateDom (main.js:518)
    at Class.updateDom (module.js:358)
`

Edit: now i noticed it disapears sometimes a few seconds and comes then back... now i try to disable other modules...

**Comment by WouterEekhout** [comment]
@a-wenzel  ~30 seconds is weird.  What did you set your `updateInterval` to?

For the error, it looks like (one of) your heating components does not has the attribute `insideTemperature`. Can you send me the JSON information from the following link? Especially the last link is important, but you will need the information from the first two links to get there. Replace YOUR_PASSWORD and YOUR_USERNAME with your Tado password and username.


1. https://my.tado.com/api/v2/me?password=YOUR_PASSWORD&username=YOUR_USERNAME , save the homes.id as HOME_ID for the next link
2. https://my.tado.com/api/v2/homes/HOME_ID/zones?password=YOUR_PASSWORD&username=YOUR_USERNAME , there will be atleast two zones for in this JSON file. Save each of them as ZONE_ID for the next step
3. https://my.tado.com/api/v2/homes/HOME_ID/zones/ZONE_ID/state?password=YOUR_PASSWORD&username=YOUR_USERNAME

**Comment by a-wenzel** [comment]
@WouterEekhout your right - the first call fails (every time) and then it takes the time to the next updateInterval - on the next updateInterval it hides for a few seconds and comes back. 

i checked all 3 Zones and they have the insideTemperature variable - but when i go down to 10 second updateInterval it fails very often... sometimes it takes 3 x 10 seconds to show up again... 

Now i have the updateInterval set to 60000 (1 Minute) most time it works but when it fails the "Tado Block" disapears and it takes his time to next succesfull request.

My Raspberry is connected over wifi - i think the script runs sometimes into a timeout (to sensitive?) and then this happens...

Edit: now i had  "tado block" two times for 1 Minute?! O_o i used your module now years but this never happend before with the old  version.

**Comment by WouterEekhout** [comment]
@a-wenzel Thank you for the research. I gave the script 3 seconds to retrieve all the information from Tado. I think what happens in your case is that the 3 seconds is not enough. This behavior is changed in commit e8f861bbca24cacaeafb34abe23bcf74768c695b. It should be solved now.

**Comment by a-wenzel** [comment]
> @a-wenzel Thank you for the research. I gave the script 3 seconds to retrieve all the information from Tado. I think what happens in your case is that the 3 seconds is not enough. This behavior is changed in commit [e8f861b](https://github.com/WouterEekhout/MMM-Tado/commit/e8f861bbca24cacaeafb34abe23bcf74768c695b). It should be solved now.

That seems to work! Thanks for your work and stay tuned.
