### ISSUE TITLE
node_modules without actual node module

### ISSUE THREAD

**Issue by mirko3000** [WouterEekhout/MMM-Tado#8]
Hey there,

just checked your changes using the node_helper. Everything works fine, except that you should not be using the node_modules folder for modules which are not actual node modules. Instead, try using e.g. this npm module:
https://github.com/mattdavis90/node-tado-client

Works almost the same as the tado-client.js you are using, but you can simply install it via
`npm install node-tado-client`

Best regards,
Mirko

**Comment by sdetweil** [comment]
i will second this.. 2 reasons

1. there is a new security fix in npm, something 6.x starting last year
if there is an npm install done and a module is NOT listed in the package.json, the package is erased!!..  (no sliming things into the system without tracking)

2. user upgraded to 2.11 and your libs are downlevel and need to be upgraded, but npm install... see 1. 

u need to add a package.json with dependencies

npm init
then npm install xyz --save

see https://forum.magicmirror.builders/topic/12953/mmm-tado-not-working

**Comment by WouterEekhout** [comment]
Thanks for the feedback. The master-branch has been updated. After `git pull`, do a `npm install`.
